name: CMake

on:
  push:
    branches:
    - main
    - debug
  pull_request:
    branches:
    - main

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt update -y
        sudo apt install -y libgflags-dev libcurl4-openssl-dev libssl-dev libaio-dev libnl-3-dev libnl-genl-3-dev e2fslibs-dev libzstd-dev
        sudo apt install -y uuid-dev libjson-c-dev libkmod-dev libsystemd-dev autoconf automake libtool libpci-dev nasm
        wget https://github.com/google/googletest/archive/refs/tags/release-1.10.0.tar.gz
        tar -zxvf release-1.10.0.tar.gz
        cd googletest-release-1.10.0/
        cmake CMakeLists.txt
        make
        sudo make install

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: |
        git submodule update --init
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTING=1 -DENABLE_DSA=0 -DENABLE_ISAL=0

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: make -j64

    - name: Unit Test
      working-directory: ${{github.workspace}}/build/output
      shell: bash
      run: ${{github.workspace}}/build/output/extfs_test